from __future__ import annotations
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from jinja2 import Template


BRIEF_TEMPLATE = """
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Case {{ case_id }} Brief</title>
<style>
  body { font-family: Arial, sans-serif; margin: 40px; }
  .header { background: #1a1a2e; color: white; padding: 20px; }
  .section { margin: 20px 0; padding: 15px; border-left: 4px solid #16213e; }
  .metric { display: inline-block; margin: 5px 10px; }
  .footer { margin-top: 40px; font-size: 0.8em; color: #666; border-top: 1px solid #ccc; padding-top: 10px; }
  table { border-collapse: collapse; width: 100%; }
  th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
  th { background-color: #16213e; color: white; }
</style>
</head>
<body>
<div class="header">
  <h1>SATYA-NET Intelligence Case Brief</h1>
  <p>Case ID: {{ case_id }} | Generated: {{ generated_at }} | Mode: {{ mode }}</p>
  {% if synthetic %}<p style="color: #ff6b6b; font-weight: bold;">WARNING SIMULATED SCENARIO no real persons or events</p>{% endif %}
</div>

<div class="section">
  <h2>Alert Summary</h2>
  <p><strong>{{ alert.headline }}</strong></p>
  <div class="metric">Priority: <strong>{{ "%.1f"|format(alert.priority) }}/100</strong></div>
  <div class="metric">Created: {{ alert.created_at }}</div>
</div>

<div class="section">
  <h2>Evidence</h2>
  <p>Ledger Merkle Root: <code>{{ merkle_root or "pending checkpoint" }}</code></p>
  <p>Record Range: seq {{ first_seq }} to {{ last_seq }}</p>
</div>

<div class="footer">
  <p>Generated by SATYA-NET v1.0 | Ledger Merkle Root: {{ merkle_root }}</p>
  <p>Verify at: /api/ledger/verify</p>
</div>
</body>
</html>
"""

CERT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>63 Draft Certificate</title>
<style>
  body { font-family: Times New Roman, serif; margin: 60px; }
  .draft-banner { background: #ff4444; color: white; padding: 15px; text-align: center; font-size: 1.2em; font-weight: bold; }
  .section { margin: 20px 0; }
  .signature-block { margin-top: 60px; }
  .signature-line { border-top: 1px solid black; width: 300px; margin-top: 40px; }
</style>
</head>
<body>
<div class="draft-banner">
  DRAFT for review and signature. Not a legal opinion. Requires counsel review before use.
</div>
<div class="draft-banner" style="background: #ff8800; font-size: 0.9em;">
  DRAFT for review and signature. Not a legal opinion.
</div>

<h1 style="text-align:center;">Certificate Under Section 63 of the Bharatiya Sakshya Adhiniyam, 2023</h1>
<h2 style="text-align:center;">[DRAFT PENDING REVIEW AND SIGNATURE]</h2>

<div class="section">
  <h3>Case Reference</h3>
  <p>Case ID: {{ case_id }}</p>
  <p>Generated: {{ generated_at }}</p>
</div>

<div class="section">
  <h3>System Description</h3>
  <p>Software: SATYA-NET v1.0 Social Media Analytics Intelligence Platform</p>
  <p>Collection method: Automated ingestion from public social media platforms (X, Telegram, Reddit, YouTube) via licensed/research-grade APIs</p>
  <p>Data integrity: SHA-256 hash chain (algorithm: SHA-256); each record is assigned a unique sequence number and hash</p>
</div>

<div class="section">
  <h3>Record Identification</h3>
  <p>Ledger sequence range: {{ first_seq }} to {{ last_seq }}</p>
  <p>Merkle root (SHA-256): <code>{{ merkle_root }}</code></p>
  <p>Public key fingerprint: {{ pubkey_id }}</p>
  <p>Timestamp range: {{ ts_range }}</p>
</div>

<div class="section">
  <h3>Verification</h3>
  <p>Verification result: {{ verify_result }}</p>
  <p>Hash algorithm: SHA-256</p>
  <p>Chain verification: Entry hashes recomputed from payload canonical JSON; chain linkage verified sequentially</p>
</div>

<div class="signature-block">
  <p><strong>[SIGNATURE BLOCKS REQUIRES RESPONSIBLE PERSON AND EXPERT SIGNATURES]</strong></p>

  <div class="signature-line"></div>
  <p>Signature of Responsible Person</p>
  <p>Name: _______________________</p>
  <p>Designation: _______________________</p>
  <p>Date: _______________________</p>

  <div class="signature-line" style="margin-top: 40px;"></div>
  <p>Signature of Expert</p>
  <p>Name: _______________________</p>
  <p>Designation: _______________________</p>
  <p>Date: _______________________</p>
</div>

<p style="margin-top: 40px; font-size: 0.8em; color: #666;">
  This document is a draft generated by SATYA-NET software. It is designed to support BSA 63 documentation.
  It must be reviewed by qualified legal counsel and signed by the appropriate responsible persons before any official use.
  No claim of court admissibility is made by this software.
</p>
</body>
</html>
"""


def generate_brief(db_path: str, case_id: int, output_dir: str = "data/cases") -> str:
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    with sqlite3.connect(db_path) as conn:
        conn.row_factory = sqlite3.Row
        case = conn.execute("SELECT * FROM cases WHERE case_id=?", (case_id,)).fetchone()
        if not case:
            raise ValueError(f"Case {case_id} not found")
        alert = conn.execute("SELECT * FROM alerts WHERE alert_id=?", (case["alert_id"],)).fetchone()
        cp = conn.execute("SELECT * FROM ledger_checkpoints ORDER BY id DESC LIMIT 1").fetchone()
        first_rec = conn.execute("SELECT seq FROM raw_records ORDER BY seq LIMIT 1").fetchone()
        last_rec = conn.execute("SELECT seq FROM raw_records ORDER BY seq DESC LIMIT 1").fetchone()

    merkle_root = cp["merkle_root"] if cp else None
    first_seq = first_rec["seq"] if first_rec else 0
    last_seq = last_rec["seq"] if last_rec else 0

    html = Template(BRIEF_TEMPLATE).render(
        case_id=case_id,
        generated_at=datetime.now(timezone.utc).isoformat(),
        mode="REPLAY",
        synthetic=True,
        alert=dict(alert) if alert else {},
        merkle_root=merkle_root,
        first_seq=first_seq,
        last_seq=last_seq,
    )
    out_path = f"{output_dir}/case_{case_id}_brief.html"
    Path(out_path).write_text(html, encoding="utf-8")

    with sqlite3.connect(db_path) as conn:
        conn.execute("UPDATE cases SET brief_path=? WHERE case_id=?", (out_path, case_id))
        conn.commit()
    return out_path


def generate_certificate(db_path: str, case_id: int, output_dir: str = "data/cases") -> str:
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    from app.ledger.verify import verify_chain
    from app.ledger.sign import Signer

    verify_result = verify_chain(db_path)
    signer = Signer()

    with sqlite3.connect(db_path) as conn:
        conn.row_factory = sqlite3.Row
        cp = conn.execute("SELECT * FROM ledger_checkpoints ORDER BY id DESC LIMIT 1").fetchone()
        first_rec = conn.execute("SELECT seq, collected_at FROM raw_records ORDER BY seq LIMIT 1").fetchone()
        last_rec = conn.execute("SELECT seq, collected_at FROM raw_records ORDER BY seq DESC LIMIT 1").fetchone()

    merkle_root = cp["merkle_root"] if cp else "N/A"
    first_seq = first_rec["seq"] if first_rec else 0
    last_seq = last_rec["seq"] if last_rec else 0
    ts_range = f"{first_rec['collected_at'] if first_rec else 'N/A'} to {last_rec['collected_at'] if last_rec else 'N/A'}"

    html = Template(CERT_TEMPLATE).render(
        case_id=case_id,
        generated_at=datetime.now(timezone.utc).isoformat(),
        first_seq=first_seq,
        last_seq=last_seq,
        merkle_root=merkle_root,
        pubkey_id=signer.pubkey_id,
        ts_range=ts_range,
        verify_result=verify_result.get("status", "UNKNOWN"),
    )
    out_path = f"{output_dir}/case_{case_id}_cert.html"
    Path(out_path).write_text(html, encoding="utf-8")

    with sqlite3.connect(db_path) as conn:
        conn.execute(
            "INSERT INTO certificates (case_id, generated_at, pdf_path, first_seq, last_seq, merkle_root) VALUES (?,?,?,?,?,?)",
            (case_id, datetime.now(timezone.utc).isoformat(), out_path, first_seq, last_seq, merkle_root),
        )
        conn.commit()
    return out_path
